[package]
name = "actix-tcp-example"
version = "0.1.0"
authors = ["adriano.pereira@tecsidel.com <admin@example.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
tokio-codec = "0.1.1"
tokio-io = "0.1.10"